### ISSUE TITLE
Permitir informar o statementDescriptor

### ISSUE THREAD

**Issue by neylorsousa** [moip/moip-sdk-java#104]
A API java no endpoint de pagamento não permite configurar o statementDescriptor. Segue abaixo os detalhes que foi escrito na solicitação de suporte MOIP #1580251:

```
A documentação cita o atributo statementDescription:

statementDescriptor
string
Identificação de sua loja na fatura de cartão de crédito do comprador. string(13)


Porém a API java (br.com.moip:java-sdk:jar:4.0.0) não consta este atributo. 
```

**Comment by bressani** [comment]
Olá, @neylorsousa !

Infelizmente a SDK de Java ainda não suporta passar o statementDescriptor para as nossas APIs.

Essa funcionalidade está no nosso backlog, mas caso queira contribuir, fique a vontade para nos enviar um PR com essa feature 😄 

Abraços!
