### ISSUE TITLE
Criação de planos para pagamento Recorrente

### ISSUE THREAD

**Issue by habeascorpse** [moip/moip-sdk-java#110]
Pessoal, como posso criar planos de pagamento recorrente, não existem nenhuma classe para isso?

**Comment by MbNakaya** [comment]
Bom dia, @habeascorpse!

No momento, a SDK não oferece suporte para pagamentos recorrentes (assinaturas). Entretanto, não descartamos a ideia de disponibilizar a integração com a **API de Assinaturas**, pela SDK, futuramente.
