### ISSUE TITLE
[WEBHOOKS] No objects to treat webhooks

### ISSUE THREAD

**Issue by Odravison** [moip/moip-sdk-java#120]
Would the devs create objects that represents the request's object webhook?

**Comment by mbnakaya** [comment]
Hi @Odravison 

To receive webhooks, you must set the notification preferences. Just it.
The Moip will send webhooks to the registered URL, it'll be based on the status you want to be notified (ex: `ORDER.CREATED`, `PAYMENT.AUTHORIZED`, `TRANSFER.COMPLETED`). Check a notification preferences example [here](https://github.com/moip/moip-sdk-java/blob/develop/src/test/java/br/com/moip/examples/NotificationPreferencesExamples.java).

> ⚠️ The way that the application will treat the webhook is responsibility of developer.

**Comment by Odravison** [comment]
Thanks @mbnakaya .
Would be nice to has an object to every event of webhook.
Your guys are open to receive PR ?! I will be able to implement this objects very soon.

For now I'm using JSONObject to encapsulate the body of webhooks.

Best regards.

**Comment by mbnakaya** [comment]
@Odravison 

Yes, I agree with you, but for priority reasons we don't put this on our _road map_, until now.
Sure!! We're totally open to receive contributions, and we appreciate it so much. I only ask you to read the `CONTRIBUTING.md`.

Best regards.
