### ISSUE TITLE
Erros na integração com moip-sdk-java

### ISSUE THREAD

**Issue by giordano221** [moip/moip-sdk-java#24]
Tentamos realizar a integração com o moip-sdk-java mas quando seguimos o exemplo que tem no git-hub, acontece alguns problemas: 

Ao tentar colocar as dependencias do maven no projeto:

Adicionar no seu pom.xml:

<dependency>
    <groupId>br.com.moip</groupId>
    <artifactId>java-sdk</artifactId>
    <version>2.0.0</version>
</dependency>

acontece de não achar a biblioteca. Pesquisei na internet nos repositorios maven e não tem a versão 2.0.0 fechada, como no exemplo, tem apenas as RCs, tipo, 2.0.0-RC1, 2.0.0-RC6.

Coloquei a RC1, depois RC2 até a RC6 e nenhuma consegue encontrar os métodos
.setOwnId("order_own_id")

ou .setCustomer(new Customer()

Por conta disso, creio que as informações estejam desatualizadas e não batem com os novos parâmetros das atualizações da lib do moip-sdk-java que está atualmente no git-hub.

Gostaríamos muito de integrar nossa plataforma com o MOIP, por isso se puder nos dá uma solução de integração com JSF ou um exemplo de integração com java, se possível com o checkout transparente, o que seria ideal para nossa plataforma, ficaremos muito gratos.

**Comment by rodrigosaito** [comment]
@giordano221 atualizei o README de acordo com o código correto. Use o último RC disponível.

Esse SDK deve ser usado com a integração v2 do Moip, hoje ainda não temos uma solução de checkout transparente para a v2.

**Comment by helio1997** [comment]
Helio Marci de Oliveira
()----(-------------- 

    Em Segunda-feira, 25 de Abril de 2016 11:37, giordano221 <notifications@github.com> escreveu:
 

 Tentamos realizar a integração com o moip-sdk-java mas quando seguimos o exemplo que tem no git-hub, acontece alguns problemas: Ao tentar colocar as dependencias do maven no projeto:Adicionar no seu pom.xml:
 br.com.moip
 java-sdk
 2.0.0
acontece de não achar a biblioteca. Pesquisei na internet nos repositorios maven e não tem a versão 2.0.0 fechada, como no exemplo, tem apenas as RCs, tipo, 2.0.0-RC1, 2.0.0-RC6.Coloquei a RC1, depois RC2 até a RC6 e nenhuma consegue encontrar os métodos
.setOwnId("order_own_id")ou .setCustomer(new Customer()Por conta disso, creio que as informações estejam desatualizadas e não batem com os novos parâmetros das atualizações da lib do moip-sdk-java que está atualmente no git-hub.Gostaríamos muito de integrar nossa plataforma com o MOIP, por isso se puder nos dá uma solução de integração com JSF ou um exemplo de integração com java, se possível com o checkout transparente, o que seria ideal para nossa plataforma, ficaremos muito gratos.—

**Comment by giordano221** [comment]
Os campos agora estão OK, mas o metodo create() não existe.

Order createdOrder = api.create(new OrderRequest())

Estou utilizando a versão 2.0.0-RC6

Obrigado.
