### ISSUE TITLE
UnauthorizedException

### ISSUE THREAD

**Issue by giordano221** [moip/moip-sdk-java#29]
Estou seguindo o exemplo para criar um pedido e ao executar está dando a seguinte exception:

Caused by: br.com.moip.exception.UnauthorizedException
    at br.com.moip.Client.doRequest(Client.java:117)
    at br.com.moip.Client.post(Client.java:60)
    at br.com.moip.api.OrderAPI.create(OrderAPI.java:17)

Esta exception se refere a este trecho de código da classe Cliente.java:

 if (responseCode == 401) {
                throw new UnauthorizedException();
            }

O codigo 401 refere-se a problemas de autenticação com as credenciais de acesso. No entanto, já conferi meu token e key de acesso e estão conforme disponíveis no meu sandbox. 

Como posso resolver essa exception?
Obrigado desde ja.

**Comment by johncordeiro** [comment]
Estou tendo o mesmo problema. Se alguém souber avisa.

**Comment by leocwolter** [comment]
Tive o mesmo problema, algum retorno??

**Comment by vlindberg** [comment]
Estou tendo o mesmo problema. Alguém conseguiu?

**Comment by caducbraga** [comment]
Alguém? Estou tendo o mesmo problema. Não consigo realizar uma simples chamada no Postman. Entrei em contato com o suporte, mas até agora não obtive resposta.

**Comment by vlindberg** [comment]
Eu tive o mesmo e resolvi. Esse problema ocorre pq eles têm que dar permissão ao seu usuário para acessar o serviço deles. Para isso, basta enviar e-mail para integracao@moip.zendesk.com e solicitar.

**Comment by guinogueiras** [comment]
@vlindberg é necessário a permissão até mesmo para utilizar o sandbox?

**Comment by caiogaspar** [comment]
Olá pessoal, caso vocês tenham criado ou criem conta em sandbox à partir de 01/06/2017, não é mais necessária a liberação. Se tiver criado antes desse dia, entre em contato com integracao@moip.com.br, para que liberem sua API.
