### ISSUE TITLE
Como gera um CreditCardHash?

### ISSUE THREAD

**Issue by jeffprestes** [moip/moip-sdk-java#33]
Olá!

Como envio os dados do cartão para vocês e daí gerar um cardhash?

Obrigado

**Comment by guinogueiras** [comment]
@jeffprestes conseguiu gerar o CreditCardHash?

**Comment by marcos150895** [comment]
Hoje tem uma forma de se gerar o cardhash, o sdk-java não tem essa opção nativamente,  para gerar esse cardhash é pelo projeto no github do moip https://github.com/moip/moip-sdk-js, caso você queira testar algo mais pontual pode acessar esse link http://moip.github.io/moip-sdk-js/ que é um exemplo funcional do moip.js.

Espero ter ajudado

**Comment by guinogueiras** [comment]
Obrigado @marcos150895
