### ISSUE TITLE
Tratar exceções?

### ISSUE THREAD

**Issue by lgertel** [moip/moip-sdk-java#40]
Gostaria de ver um exemplo de como tratar exceções na API. A documentação não está muito clara...

Por exemplo:  Tentar salvar um usuário já existente.

**Comment by ralphavalon** [comment]
@lgertel Eu passei pelo mesmo problema. Fui entender como funciona e criei um Pull Request para o MOIP. De qualquer maneira, você consegue ver a documentação atualizada nesse link: https://github.com/ralphavalon/moip-sdk-java

Basicamente é assim:

```java
try {
 Payment createdPayment = api.payment().create(
        //...
    );
} catch(UnexpectecException e) {
  //StatusCode >= 500
} catch(ValidationException e) {
  //StatusCode entre 400 e 499 (exceto 401)
}
```

**Comment by caiogaspar** [comment]
As exceções são tratadas exatamente da forma que o @ralphavalon relatou. A única diferença é que na nova versão da SDK (`3.0.0`) o erro 500 é tratado com ```UnexpectedException``` e não mais ```UnexpectecException```.
