### ISSUE TITLE
API para gerenciar cartões de créditos do cliente

### ISSUE THREAD

**Issue by humbertosales** [moip/moip-sdk-java#60]
Pessoal, 
como faço para cadastrar e deletar cartões do cliente. Só encontrei api de efetuar pedindo conjugado com cartão de crédito...

Preciso da inclusão de cartão para poder fazer pedido futuros sem o usuário ter que cadastrar tudo novamente....

Confesso que estou achando o SDK Java bastante incompleto... estou errado?

**Comment by caiogaspar** [comment]
E aí @humbertosales, tudo bem?
Sou do time aqui do @moip que está cuidando das SDK's e nós estamos trabalhando nessa feature de cartões e em outras também para a SDK de java. 

Estamos com previsão de lançamento da nova versão da SDK com todas essas features já na próxima semana!

Clica em 'Watch' no nosso repositório pra acompanhar a evolução da nossa SDK!

Abraço,
Caio Gaspar

**Comment by humbertosales** [comment]
Excelente caio!! 
Eu estava implementando tudo na mão, já estava decepcionado. 
Por favor, não esqueçam de incluir o método DELETE no Client....
