### ISSUE TITLE
Exceções da biblioteca não possuem mensagem nem código indicativo

### ISSUE THREAD

**Issue by humbertosales** [moip/moip-sdk-java#64]
Prezados,

As exceções lançadas pela biblioteca não possuem descrição (message ou detailMessage)... a única coisa que retorna é responseCode 400. 

Erro 400 é erro do cliente, mas como saber qual é o erro se não tem informação descritiva?

Tentei criar um cliente  com toda as informações do exemplo, porém estou recebendo uma ValidationException sem nenhuma informação útil para tratar o erro.

Alguém poderia me explicar como usar?

**Comment by caiogaspar** [comment]
Olá @humbertosales,
As exceções geradas pela API possuem código e mensagem (https://dev.moip.com.br/reference#erros). Para ver as mensagens geradas, você pode fazer algo semelhante a isso:
```java
try {
  //...
} catch (ValidationException exception) {
  System.out.println(exception.getErrors().toString());
}
```
Abs,
Caio Gaspar
