### ISSUE TITLE
[BANKING] Update and delete

### ISSUE THREAD

**Issue by caiogaspar** [moip/moip-sdk-java#77]
The following features should be added to support Transfers:
 - [ ] Update a specific Bank Account
 - [ ] Delete a specific Bank Account

You can find the official documentation [here](https://documentao-moip.readme.io/v2.0/reference#contas-bancárias)!

<hr/>

### Implementation Tips:
You can draw inspiration from [this PR](https://github.com/moip/moip-sdk-java/pull/56). Don't forget to write good tests, and to document it on our `README`

**Comment by andredgusmao** [comment]
I send you a pull request for this feature.
