### ISSUE TITLE
[ENTRIES] List, Show

### ISSUE THREAD

**Issue by joaolucasl** [moip/moip-sdk-java#79]
The following features should be added to support Entries:
 - [ ] Show a specific entry
 - [ ] List all entries

You can find the official API documentation for Entries [here (PT-BR)](https://documentao-moip.readme.io/v2.0/reference#lançamentos)!

<hr/>

### Implementation Tips:
You can draw inspiration from [this PR](https://github.com/moip/moip-sdk-java/pull/56). Don't forget to write good tests, and to document the feature in our `README`.

**Comment by mhdsmr2** [comment]
Do I have to create a new class for entries? Because I can't find one.

**Comment by mhdsmr2** [comment]
Can you tell me where's the Entries' java file?

**Comment by mmalaquiasdev** [comment]
@joaolucasl Can you detail more the issue?

Do you want a new Client API, EntryApi ?

**Comment by bressani** [comment]
@mmalaquiasdev yes! The EntryAPI, the reference of the EntryAPI in API.java, the resource that is going to be mapped when the client receives the response, and also unit tests and documentation in our README. 😃
