### ISSUE TITLE
Full support to 'Amount' from Payment

### ISSUE THREAD

**Issue by caiogaspar** [moip/moip-sdk-java#81]
Currently is only possible get total from [Amount](https://github.com/moip/moip-sdk-java/blob/develop/src/main/java/br/com/moip/resource/Amount.java) node when payment (JSON) is received from API.

We need methods to get the following properties too:
 - [ ] fees
 - [ ] refunds
 - [ ] liquid
 - [ ] currency

You can find the official API documentation for Payments [here (PT-BR)](https://dev.moip.com.br/reference#pagamentos)!

<hr/>

### Implementation Tips:
The methods should be similar to `getTotal` from [Amount](https://github.com/moip/moip-sdk-java/blob/develop/src/main/java/br/com/moip/resource/Amount.java).

**Comment by vkdrn** [comment]
@caiogaspar Done it!
