### ISSUE TITLE
Como realizar um pagamento com cartão já cadastrado?

### ISSUE THREAD

**Issue by humbertosales** [moip/moip-sdk-java#82]
Prezados, 

Utilizei o próprio exemplo do **readme.md** para cadastrar um cartão de crédito e armazenei o ID do cartão, porém no momento do pagamento não consigo utilizar o ID do cartão criado.

A API Rest permite realizar pagamento somente com o ID do cartão, mas na API Java não permite.

Por gentileza, como devo fazer?

**Comment by caiogaspar** [comment]
Olá @humbertosales, hoje ainda não é possível realizar esse tipo de operação usando a SDK de Java, pois falta um método para 'setar' o ID do cartão de crédito no `CreditCardRequest`. Isso está no backlog para implementarmos no próximo sprint, porém, enquanto o sprint não chega, já abrimos a issue #85 para caso alguém queira se antecipar e contribuir com a nossa SDK!

Abs!
