### ISSUE TITLE
Como realizar pagamento com recebedor secundário (SPLIT)?

### ISSUE THREAD

**Issue by humbertosales** [moip/moip-sdk-java#83]
Prezados, 
não consegui entender nesta nova API 3.1 como fazer um pagamento com vários recebedores, split do pagamento.

Poderiam explicar?

**Comment by caiogaspar** [comment]
Olá @humbertosales, tudo bem?
Pra fazer um split de pagamentos você deve adicionar os recebedores aos pedidos usando o método `addReceiver`, por exemplo:
```java
Order createdOrder = api.create(new OrderRequest()
    .ownId("order_own_id")
    .addItem("Nome do produto", 1, "Mais info...", 10000)
    .customer(new CustomerRequest()
        .ownId("customer_own_id")
        .fullname("Jose da Silva")
        .email("sandbox_v2_1401147277@email.com")
    )
    .addReceiver(new ReceiverRequest()
        .secondary("MPA-123123123",
        new AmountRequest().fixed(100), false)
    )
);
```

Nesse caso nós adicionamos um recebedor secundário, recebendo o valor fixo de 1,00. 

Também é possível:
- Adicionar recebedores primários usando o `primary` no lugar do `secondary`;
- Usar valores percentuais ao invés do fixo trocando o `fixed` por `percentual`; 
- Determinar quem é o pagador da taxa passando `true` ao invés de `false` no último parâmetro do `addReceiver`.

Se tiver mais dúvidas, você pode entrar em contato com nossos analistas pelo integracao@moip.com.br.

Abs!

**Comment by humbertosales** [comment]
Obrigado!!!

**Comment by humbertosales** [comment]
@caiogaspar ,
Como cadastrar um Recebedor Secundário?

Não estou encontrando a API (nem Java nem Rest). Acredito que não haja ainda ela em Java, mas existe em Rest? Onde encontro a documentação?
