### ISSUE TITLE
Support to use an existing credit card when create a payment

### ISSUE THREAD

**Issue by caiogaspar** [moip/moip-sdk-java#85]
To support using an existing credit card when create a payment, is needed: to create a property and a setter method to credit card ID in the class [`CreditCardRequest`](https://github.com/moip/moip-sdk-java/blob/develop/src/main/java/br/com/moip/request/CreditCardRequest.java).

You can find the official API documentation to create a payment [here (PT-BR)](https://dev.moip.com.br/reference#criar-pagamento)!

<hr/>

### Implementation Tips:
See the implementation of `hash` property in  [`CreditCardRequest`](https://github.com/moip/moip-sdk-java/blob/develop/src/main/java/br/com/moip/request/CreditCardRequest.java), the class has a setter (`hash`) and getter (`getHash`).
So all you have to do:
- Add the property `id` in the class;
- Create the setter and getter methods.
- It's done :)

**Comment by vkdrn** [comment]
@caiogaspar Hi. I want to take this issue.

**Comment by Polovinsky** [comment]
I'll implement but need more details about the feature

**Comment by caiogaspar** [comment]
@vkdrn @Polovinsky I edited the description adding more details about what is needed ;)

**Comment by Polovinsky** [comment]
Cool!

**Comment by vkdrn** [comment]
Done it

**Comment by danieldhp** [comment]
Any idea when this patch will be released?
