### ISSUE TITLE
Como consultar customers por OwnID?

### ISSUE THREAD

**Issue by humbertosales** [moip/moip-sdk-java#90]
Prezados,

``getAPI().customer().get()`` só consulta pelo ID do Moip... 

Como podemos consultar pelo OwnID?

**Comment by joaolucasl** [comment]
Oi @humbertosales 
Ainda não temos essa feature na SDK. O modo de buscar por `own_id` na nossa API REST seria realizando uma requisição `v2/customers?q=own_id`. 

Pull requests adicionando essa feature são bem vindos :)
